apiVersion: v1
kind: Pod
metadata:
  name: ${K8S_POD_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    loader-cluster-name: ${K8S_LOADER_CLUSTER_NAME}
    loader-name: ${K8S_LOADER_NAME}
spec:
  # NOTE: 'affinity' will be updated in the code.
  affinity: {}
  # NOTE: we cannot use hostnetworking because we run lots of loader pods on a single K8S node.
  #       Moreover, it is not needed because pods get IP addresses from the K8S nodes network.
  hostNetwork: false
  # NOTE: 'restartPolicy' must be set to 'Never' because we should never restart stress threads
  restartPolicy: Never
  containers:
    - name: loader
      image: ${DOCKER_IMAGE_WITH_TAG}
      tty: true
      # NOTE: livenessProbe will allow us to stop loader-container execution not deleting pod.
      #       Presence of a stopped pod will allow us to get it's logs anytime.
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/keep_running
        initialDelaySeconds: 1
        periodSeconds: 3
      command:
        # NOTE: use bash wrapper because our stress commands do not use full binary paths.
        - /bin/bash
        - -c
        - "touch /tmp/keep_running ; cp /etc/scylla/cassandra/logback-tools.xml .; ${K8S_POD_COMMAND}"
