apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${K8S_LOADER_CLUSTER_NAME}
  namespace: ${K8S_NAMESPACE}
spec:
  selector:
    matchLabels:
      loader-cluster-name: ${K8S_LOADER_CLUSTER_NAME}
  serviceName: ${K8S_LOADER_CLUSTER_NAME}
  replicas: ${N_LOADERS}
  template:
    metadata:
      labels:
        loader-cluster-name: ${K8S_LOADER_CLUSTER_NAME}
    spec:
      # NOTE: 'affinity' will be updated in the code.
      affinity: {}
      containers:
        - name: loader
          image: ${DOCKER_IMAGE_WITH_TAG}
          tty: true
          command:
            - /bin/bash
            - -c
            - "cp /etc/scylla/cassandra/logback-tools.xml . ; cat"
          resources:
            limits:
              cpu: ${POD_CPU_LIMIT}
              memory: ${POD_MEMORY_LIMIT}
            requests:
              cpu: ${POD_CPU_LIMIT}
              memory: ${POD_MEMORY_LIMIT}
      hostNetwork: false
